version: '3.8'

services:
  # Our Laravel API Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_api_app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80" # Access your API locally via http://localhost:8000
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

# Networks to allow containers to talk to each other
networks:
  laravel_network:
    driver: bridge
